import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { citizenApi } from "../api/citizen";
import { saveBlob } from "../api/client";
import { DemoNotice, EmptyState, ErrorMessage, formatDate, Loading, SuccessMessage } from "../components/Ui";
import type { ApplicationDetail, GeneratedDocument, MockIssuedDocument } from "../types/api";
import { compressDocumentForUpload, compressionSummary } from "../utils/document-compression";

const documentTypes = ["UNKNOWN", "AADHAAR", "PAN", "TRADE_LICENCE", "INCOME_CERTIFICATE", "DOMICILE_CERTIFICATE", "BIRTH_CERTIFICATE", "PROPERTY_DOCUMENT", "OTHER"];

function mockDocumentField(document: MockIssuedDocument, field: string): string | null {
  const value = document.structuredFields?.[field];
  return typeof value === "string" && value.trim() ? value : null;
}

export function ApplicationDocumentsPage() {
  const { applicationId = "" } = useParams(); const app = useRequest(() => citizenApi.application(applicationId), [applicationId]); const docs = useRequest(() => citizenApi.documents(applicationId), [applicationId]); const [file, setFile] = useState<File | null>(null); const [requirementId, setRequirementId] = useState(""); const [expectedType, setExpectedType] = useState("UNKNOWN"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [analysis, setAnalysis] = useState<{ filename: string; value: Record<string, unknown> } | null>(null);
  const upload = async (event: FormEvent) => { event.preventDefault(); if (busy) return; if (!file) { setError("Choose a PDF, JPG, JPEG, or PNG file first."); return; } setBusy(true); setError(""); try { const compression = await compressDocumentForUpload(file); const uploadFile = compression.file; if (uploadFile.size > 10 * 1024 * 1024) { setError("The selected file exceeds the 10 MB backend limit."); return; } const form = new FormData(); form.append("file", uploadFile, uploadFile.name); if (requirementId) form.append("requirementId", requirementId); if (expectedType !== "UNKNOWN") form.append("expectedDocumentType", expectedType); await citizenApi.upload(applicationId, form); setFile(null); const summary = compressionSummary(compression); setSuccess(`${summary ? `${summary} ` : ""}Document uploaded. You may run deterministic demo analysis while the application is a draft.`); await Promise.all([docs.reload(), app.reload()]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Upload failed."); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!window.confirm("Remove this draft document? This action cannot be undone.")) return; setError(""); try { await citizenApi.deleteDocument(id); setSuccess("Document removed."); await Promise.all([docs.reload(), app.reload()]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to remove document."); } };
  const analyze = async (id: string, filename: string) => { setError(""); try { const result = await citizenApi.analyze(id); setAnalysis({ filename, value: result.analysis }); setSuccess("Deterministic demo analysis completed."); await Promise.all([docs.reload(), app.reload()]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Analysis could not be completed."); } };
  if (app.loading || docs.loading) return <Loading label="Loading documents" />; if (app.error || !app.data) return <ErrorMessage message={app.error || "Application not found."} />; const application = app.data.application; const isDraft = application.status === "DRAFT";
  return <><Link className="back-link" to={`/applications/${applicationId}`}>Back to application</Link><section className="hero split"><div><p className="eyebrow">APPLICATION DOCUMENTS</p><h1>{application.service.name}</h1><p>Upload and analyse documents only while this application is a draft.</p></div></section><DemoNotice>{"Analysis is deterministic demo OCR. It does not authenticate documents, issue a government verification, or retain raw OCR text."}</DemoNotice>{!isDraft && <ErrorMessage message="Document upload, removal, and analysis are unavailable because this application is no longer a draft." />}{isDraft && <form className="card form-stack" onSubmit={upload}><h2>Upload document</h2><div className="form-grid"><label>Service requirement<select value={requirementId} onChange={(e) => setRequirementId(e.target.value)}><option value="">No requirement selected</option>{application.service.requirements.map((requirement) => <option key={requirement.requirementId} value={requirement.requirementId}>{requirement.name}{requirement.isRequired ? " (required)" : ""}</option>)}</select></label><label>Expected document type<select value={expectedType} onChange={(e) => setExpectedType(e.target.value)}>{documentTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="file-field">File (PDF, JPG, JPEG, PNG - max 10 MB)<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={(e) => setFile(e.target.files?.[0] ?? null)} required /></label></div><button className="button primary" disabled={busy}>{busy ? "Uploading..." : "Upload document"}</button></form>}{error && <ErrorMessage message={error} />}{success && <SuccessMessage message={success} />}<section className="card"><h2>Uploaded documents</h2>{docs.error && <ErrorMessage message={docs.error} />}{docs.data?.documents.length === 0 && <EmptyState title="No documents uploaded" text="Upload the document files required for this draft application." />}{docs.data?.documents.map((document) => <article className="document-row" key={document.documentId}><div><strong>{document.originalFilename}</strong><p>{document.documentType} · {document.status} · {(document.fileSizeBytes / 1024).toFixed(1)} KB</p></div><div className="inline-actions">{isDraft && <button className="button secondary" onClick={() => void analyze(document.documentId, document.originalFilename)}>Analyse</button>}{isDraft && <button className="button danger" onClick={() => void remove(document.documentId)}>Remove</button>}</div></article>)}</section>{analysis && <AnalysisCard title={analysis.filename} analysis={analysis.value} close={() => setAnalysis(null)} />}</>;
}

export function AnalysisCard({ title, analysis, close }: { title: string; analysis: Record<string, unknown>; close?: () => void }) {
  const fields = analysis.fields as Record<string, unknown> | undefined; const issues = Array.isArray(analysis.detectedIssues) ? analysis.detectedIssues : []; const missing = Array.isArray(analysis.missingFields) ? analysis.missingFields : [];
  return <section className="card analysis-card"><div className="section-heading"><div><p className="eyebrow">DEMO DOCUMENT ANALYSIS</p><h2>{title}</h2></div>{close && <button className="button secondary" onClick={close}>Close analysis</button>}</div><DemoNotice>{String(analysis.recommendation ?? "This deterministic result is not document authenticity verification.")}</DemoNotice><div className="analysis-grid"><p><strong>Detected type:</strong> {String(analysis.documentType ?? "Unknown")}</p><p><strong>Confidence:</strong> {typeof analysis.confidence === "number" ? `${Math.round(analysis.confidence * 100)}%` : "Not available"}</p><p><strong>Readable:</strong> {String(analysis.isReadable ?? "Not available")}</p><p><strong>Signature:</strong> {String(analysis.signatureDetected ?? "NOT_AVAILABLE")}</p><p><strong>Seal:</strong> {String(analysis.sealDetected ?? "NOT_AVAILABLE")}</p></div>{fields && <><h3>Extracted fields</h3><dl className="field-list">{Object.entries(fields).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value ? String(value) : "Not found"}</dd></div>)}</dl></>}<h3>Detected issues</h3>{issues.length ? <ul>{issues.map((item, index) => <li key={index}>{String(item)}</li>)}</ul> : <p>No detected issues were returned.</p>}<h3>Missing fields</h3>{missing.length ? <ul>{missing.map((item, index) => <li key={index}>{String(item)}</li>)}</ul> : <p>No missing fields were returned.</p>}</section>;
}

function CompletionDocumentsSection() {
  const [page, setPage] = useState(1); const apps = useRequest(() => citizenApi.applications(`?page=${page}&limit=10`), [page]); const [documents, setDocuments] = useState<Array<GeneratedDocument & { applicationStatus: ApplicationDetail["status"] }>>([]); const [loadingDocs, setLoadingDocs] = useState(false); const [error, setError] = useState(""); const navigate = useNavigate();
  useEffect(() => { const load = async () => { if (!apps.data) return; setLoadingDocs(true); setError(""); try { const sets = await Promise.all(apps.data.applications.map(async (application) => (await citizenApi.generated(application.applicationId)).documents.map((document) => ({ ...document, applicationStatus: application.status })))); setDocuments(sets.flat()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load issued demo documents."); } finally { setLoadingDocs(false); } }; void load(); }, [apps.data]);
  const download = async (document: GeneratedDocument) => { setError(""); try { saveBlob(await citizenApi.downloadGenerated(document.generatedDocumentId), document.originalFilename ?? "janseva-x-demo-document.pdf"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Document download failed."); } };
  return <><section className="hero"><p className="eyebrow">ISSUED DEMO DOCUMENTS</p><h1>Completion documents</h1><p>Only actual server-issued demo completion documents are shown.</p></section><DemoNotice>{"These documents are prototypes. They are not government-issued, legally valid, or a general document vault."}</DemoNotice>{(apps.loading || loadingDocs) && <Loading label="Loading issued demo documents" />}{(apps.error || error) && <ErrorMessage message={apps.error || error} />}{!apps.loading && !loadingDocs && !error && documents.length === 0 && <EmptyState title="No issued demo documents" text="Documents appear here only after an external workflow approves an application and issues a demo completion certificate." />}{documents.map((document) => <article className="document-row card" key={document.generatedDocumentId}><div><p className="eyebrow">{document.documentType}</p><h2>{document.originalFilename ?? "Demo completion document"}</h2><p>{document.signatureStatus} · Generated {new Date(document.generatedAt).toLocaleDateString("en-IN")}</p></div><div className="inline-actions"><button className="button secondary" onClick={() => void download(document)}>Download PDF</button>{document.applicationStatus === "APPROVED" && document.signatureStatus !== "SIGNED" && <button className="button primary" onClick={() => navigate(`/documents/${document.generatedDocumentId}/sign?application=${document.applicationId}`)}>Mock e-sign</button>}</div></article>)}{apps.data && apps.data.pagination.totalPages > 1 && <div className="pagination"><button className="button secondary" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Application page {page} of {apps.data.pagination.totalPages}</span><button className="button secondary" disabled={page >= apps.data.pagination.totalPages} onClick={() => setPage((value) => value + 1)}>Next</button></div>}</>;
}

export function IssuedDocumentsPage() {
  const issued = useRequest(() => citizenApi.issuedDocuments(), []);
  return <><section className="hero"><p className="eyebrow">ISSUED DEMO DOCUMENTS</p><h1>My issued documents</h1><p>View the mock documents linked to your JANSEVA-X demo profile.</p></section><DemoNotice>{"All documents in the mock registry are fictional JANSEVA-X demo data. They are not government-issued or legally valid."}</DemoNotice><section className="card mock-registry"><p className="eyebrow">MOCK ISSUED DOCUMENTS</p><h2>Demo document registry</h2>{issued.loading && <Loading label="Loading mock issued documents" />}{issued.error && <ErrorMessage message={issued.error} />}{!issued.loading && !issued.error && issued.data?.documents.length === 0 && <EmptyState title="No mock issued documents" text="No mock documents are linked to this demo citizen profile." />}{issued.data?.documents.map((document) => <MockIssuedDocumentCard document={document} key={document.documentId} />)}</section><CompletionDocumentsSection /></>;
}

function MockIssuedDocumentCard({ document }: { document: MockIssuedDocument }) {
  const holderName = mockDocumentField(document, "holderName") ?? "DEMO CITIZEN";
  const reference = mockDocumentField(document, "documentReference") ?? document.documentCode;
  const dateOfBirth = mockDocumentField(document, "dateOfBirth");
  const address = mockDocumentField(document, "address");
  const qualification = mockDocumentField(document, "qualification");
  return <article className="mock-issued-document-card"><header className="mock-issued-document-header"><div><p className="eyebrow">JANSEVA-X DEMO DOCUMENT REGISTRY</p><h3>{document.displayName}</h3><p className="mock-document-type">{document.documentType.replaceAll("_", " ")}</p></div><span className="mock-document-badge">DEMO / PROTOTYPE</span></header><p className="mock-document-disclaimer">NOT A GOVERNMENT DOCUMENT</p><dl className="mock-document-details"><div><dt>Demo holder</dt><dd>{holderName}</dd></div><div><dt>Registry reference</dt><dd>{reference}</dd></div><div><dt>Demo issuer</dt><dd>{document.issuer}</dd></div><div><dt>Issue date</dt><dd>{formatDate(document.issueDate)}</dd></div>{document.expiryDate && <div><dt>Expiry date</dt><dd>{formatDate(document.expiryDate)}</dd></div>}{dateOfBirth && <div><dt>Date of birth</dt><dd>{formatDate(dateOfBirth)}</dd></div>}{address && <div className="mock-document-wide"><dt>Demo address</dt><dd>{address}</dd></div>}{qualification && <div className="mock-document-wide"><dt>Qualification</dt><dd>{qualification}</dd></div>}</dl><footer className="mock-issued-document-footer"><div><strong>Status: {document.status}</strong><span>Issued only for the JANSEVA-X prototype.</span></div><div className="demo-reference-marker" aria-label="Non-scannable demo registry reference"><span>DEMO REGISTRY REF</span><code>|||| {document.documentCode} ||||</code><small>Not a QR code or government credential</small></div><div className="demo-issuer-mark"><strong>DEMO ISSUER MARK</strong><span>No legal signature or seal</span></div></footer></article>;
}

export function SigningPage() {
  const { documentId = "" } = useParams(); const [params] = useSearchParams(); const applicationId = params.get("application") ?? ""; const [session, setSession] = useState<Awaited<ReturnType<typeof citizenApi.startSigning>> | null>(null); const [accepted, setAccepted] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const navigate = useNavigate();
  const start = async () => { setBusy(true); setError(""); try { setSession(await citizenApi.startSigning(documentId)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to start mock e-sign."); } finally { setBusy(false); } };
  const complete = async () => { if (!session) return; setBusy(true); setError(""); try { await citizenApi.completeSigning(session.sessionId, session.signingChallenge, session.consent.version); setSuccess("Mock e-sign completed."); window.setTimeout(() => navigate(applicationId ? `/applications/${applicationId}` : "/documents"), 600); } catch (caught) { setError(caught instanceof Error ? caught.message : "Mock e-sign could not be completed."); } finally { setBusy(false); } };
  return <><Link className="back-link" to={applicationId ? `/applications/${applicationId}` : "/documents"}>Back</Link><section className="hero"><p className="eyebrow">MOCK E-SIGN</p><h1>Demo completion document consent</h1><p>Start only for a server-issued unsigned demo completion document on an approved application.</p></section><DemoNotice>{"This is not a legally valid electronic signature and does not use a government identity or e-sign provider."}</DemoNotice>{error && <ErrorMessage message={error} />}{success && <SuccessMessage message={success} />}{!session ? <button className="button primary" onClick={() => void start()} disabled={busy}>{busy ? "Starting..." : "Start mock e-sign"}</button> : <section className="card form-stack"><h2>{session.document.originalFilename ?? session.document.documentType}</h2><p>{session.disclaimer}</p><p className="muted">Session expires {new Date(session.expiresAt).toLocaleTimeString("en-IN")}</p><div className="consent-text">{session.consent.text}</div><label className="checkbox"><input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} />I accept the exact mock e-sign consent shown above.</label><button className="button primary" onClick={() => void complete()} disabled={!accepted || busy}>{busy ? "Completing..." : "Complete mock e-sign"}</button></section>}</>;
}

function useRequest<T>(request: () => Promise<T>, dependencies: unknown[]) { const [data, setData] = useState<T | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = async () => { setLoading(true); setError(""); try { setData(await request()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load this page."); } finally { setLoading(false); } }; useEffect(() => { void load(); }, dependencies); return { data, loading, error, reload: load }; }
