import "../repositories/employee.repository.extensions";
import type { Request, Response } from "express";
import { EmployeeService } from "../services/employee.service";
import { presentApplication, presentApplicationReview, presentCompletedItem, presentIdentityVerification, presentQueueItem, presentRegistryItem } from "../utils/response-presenters";
const service = new EmployeeService(); const applicationId = (request: Request) => (request.validated!.params as any).applicationId;
export async function queue(request: Request, response: Response): Promise<void> { const query = request.validated!.query as any; const result = await service.queue(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", query); response.json({ success: true, data: { applications: result.applications.map(presentRegistryItem), pagination: { page: result.page, limit: result.limit, total: result.total, totalPages: result.totalPages } } }); }
export async function completed(request: Request, response: Response): Promise<void> { const query = request.validated!.query as any; const result = await service.completed(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", query); response.json({ success: true, data: { applications: result.applications.map(presentCompletedItem), pagination: { page: result.page, limit: result.limit, total: result.total, totalPages: result.totalPages } } }); }
export async function detail(request: Request, response: Response): Promise<void> { response.json({ success: true, data: { application: presentApplication(await service.detail(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", applicationId(request))) } }); }
export async function reviewDetail(request: Request, response: Response): Promise<void> { response.json({ success: true, data: { application: presentApplicationReview(await service.reviewDetail(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", applicationId(request))) } }); }
export async function reviewIdentityVerification(request: Request, response: Response): Promise<void> { const params = request.validated!.params as any; const body = request.validated!.body as any; const verification = await service.reviewIdentityVerification(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", params.applicationId, params.verificationId, body.action, body.note); response.json({ success: true, data: { verification: presentIdentityVerification(verification) } }); }
export async function claim(request: Request, response: Response): Promise<void> { response.json({ success: true, data: { application: presentApplication(await service.claimApplication(request.auth!.userId, applicationId(request))) } }); }
export async function release(request: Request, response: Response): Promise<void> { response.json({ success: true, data: { application: presentQueueItem(await service.release(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", applicationId(request))) } }); }
export async function assign(request: Request, response: Response): Promise<void> { response.json({ success: true, data: { application: presentApplication(await service.assign(request.auth!.userId, applicationId(request), (request.validated!.body as any).officerId)) } }); }
export async function start(request: Request, response: Response): Promise<void> { response.json({ success: true, data: { application: presentApplication(await service.start(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", applicationId(request))) } }); }
export async function decide(request: Request, response: Response): Promise<void> { const body = request.validated!.body as any; response.json({ success: true, data: { application: presentApplication(await service.decision(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", applicationId(request), body.status, body.note)) } }); }
export async function issueCertificate(request: Request, response: Response): Promise<void> { const authorization = request.header("authorization"); if (!authorization) throw new Error("Authorization header required"); response.status(201).json({ success: true, data: { document: await service.issueGeneratedDocument(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", applicationId(request), authorization) } }); }
export async function history(request: Request, response: Response): Promise<void> { const application = await service.detail(request.auth!.userId, request.auth!.role as "OFFICER" | "ADMIN", applicationId(request)); response.json({ success: true, data: { history: presentApplication(application).history } }); }
