import { Router } from "express";
import { asyncHandler } from "../utils/async-handler";
import { validate } from "../middleware/validate";
import { requireActiveAccount, requireAuth, requireRole } from "../middleware/require-auth";
import { autoAttachExamDocuments, createExamApplication, createExamSubmission, getExam, getExamApplication, listExamApplications, listExams, setExamReminder, submitExamApplication, updateExamApplication, validateExamApplication } from "../controllers/exam.controller";
import { createExamApplicationSchema, examApplicationActionSchema, examApplicationIdSchema, examIdSchema, examSubmissionSchema, updateExamApplicationSchema } from "../validators/exam.validators";
export const examRouter = Router();
examRouter.get("/exams", asyncHandler(listExams));
examRouter.get("/exams/:examId", validate(examIdSchema), asyncHandler(getExam));
examRouter.use("/exam-applications", requireAuth, requireActiveAccount, requireRole("CITIZEN"));
examRouter.post("/exam-applications", validate(createExamApplicationSchema), asyncHandler(createExamApplication));
examRouter.get("/exam-applications", asyncHandler(listExamApplications));
examRouter.get("/exam-applications/:applicationId", validate(examApplicationIdSchema), asyncHandler(getExamApplication));
examRouter.patch("/exam-applications/:applicationId", validate(updateExamApplicationSchema), asyncHandler(updateExamApplication));
examRouter.post("/exam-applications/:applicationId/auto-attach", validate(examApplicationActionSchema), asyncHandler(autoAttachExamDocuments));
examRouter.post("/exam-applications/:applicationId/validate", validate(examApplicationActionSchema), asyncHandler(validateExamApplication));
examRouter.post("/exam-applications/:applicationId/submission", validate(examSubmissionSchema), asyncHandler(createExamSubmission));
examRouter.post("/exam-applications/:applicationId/submit", validate(examApplicationActionSchema), asyncHandler(submitExamApplication));
examRouter.post("/exam-applications/:applicationId/reminder", validate(examApplicationActionSchema), asyncHandler(setExamReminder));
