import { presentAdvisoryDiagnostics } from "./advisory-diagnostics";

export function presentQueueItem(app: any) { return { applicationId: app.id, applicationNumber: app.applicationNumber, status: app.status, reviewStatus: app.reviewStatus, service: { serviceId: app.service.id, name: app.service.name, slug: app.service.slug, isPrototype: app.service.isPrototype }, assignedOfficer: app.assignedOfficer ? { officerId: app.assignedOfficer.id, displayName: app.assignedOfficer.user.displayName } : null, submittedAt: app.submittedAt, createdAt: app.createdAt, updatedAt: app.updatedAt }; }
export function presentRegistryItem(app: any) { return { ...presentQueueItem(app), citizen: { citizenId: app.citizen.id, fullName: app.citizen.fullName, city: app.citizen.city, state: app.citizen.state } }; }
export function presentCompletedItem(app: any) { return { ...presentRegistryItem(app), completedAt: app.statusHistory[0]?.createdAt ?? null, generatedDocuments: presentGeneratedDocuments(app.generatedDocuments) }; }
export function presentIdentityVerification(verification: any) { return { verificationId: verification.id, type: verification.type, status: verification.status, failureReason: verification.failureReason, verifiedAt: verification.verifiedAt, createdAt: verification.createdAt, updatedAt: verification.updatedAt }; }
function presentMockIssuedDocumentAttachments(attachments: any[] | undefined, requirements: Iterable<any>) { const requirementNames = new Map(Array.from(requirements, (requirement: any) => [requirement.id, requirement.name])); return (attachments ?? []).map((attachment: any) => ({ attachmentId: attachment.id, requirementId: attachment.requirementId, requirementName: requirementNames.get(attachment.requirementId) ?? null, attachedAt: attachment.attachedAt, source: "MOCK_ISSUED_DOCUMENT" as const, mockIssuedDocument: { documentId: attachment.mockIssuedDocument.id, documentType: attachment.mockIssuedDocument.documentType, displayName: attachment.mockIssuedDocument.displayName, issuer: attachment.mockIssuedDocument.issuer, issueDate: attachment.mockIssuedDocument.issueDate, expiryDate: attachment.mockIssuedDocument.expiryDate, status: attachment.mockIssuedDocument.status, isDemo: attachment.mockIssuedDocument.isDemo, mode: "DEMO/PROTOTYPE" as const } })); }
function presentGeneratedDocuments(documents: any[] | undefined) { return (documents ?? []).map((document: any) => { const session = document.signingSessions?.[0]; return { generatedDocumentId: document.id, documentType: document.documentType, documentName: document.originalFilename ?? document.documentType, signatureStatus: document.signatureStatus, generatedAt: document.generatedAt, signedAt: document.signedAt, signingSession: session ? { state: session.status, expiresAt: session.expiresAt, completedAt: session.completedAt } : null, mode: "DEMO/PROTOTYPE" as const }; }); }
export function presentApplicationReview(app: any) {
  const requirements = new Map<string, any>(app.service.requirements.map((requirement: any) => [requirement.id, requirement]));
  return {
    applicationId: app.id,
    applicationNumber: app.applicationNumber,
    status: app.status,
    reviewStatus: app.reviewStatus,
    correctionReason: app.correctionReason,
    applicationData: app.formData,
    submittedAt: app.submittedAt,
    createdAt: app.createdAt,
    updatedAt: app.updatedAt,
    applicant: { citizenId: app.citizen.id, fullName: app.citizen.fullName, city: app.citizen.city, state: app.citizen.state },
    service: { serviceId: app.service.id, name: app.service.name, slug: app.service.slug, description: app.service.description, isPrototype: app.service.isPrototype, requirements: app.service.requirements.map((requirement: any) => ({ requirementId: requirement.id, name: requirement.name, description: requirement.description, isRequired: requirement.isRequired, sortOrder: requirement.sortOrder })) },
    assignment: app.assignedOfficer ? { officerId: app.assignedOfficer.id, displayName: app.assignedOfficer.user.displayName, department: app.assignedOfficer.department, designation: app.assignedOfficer.designation, assignedAt: app.assignedAt, reviewedAt: app.reviewedAt } : null,
    documents: app.applicationDocuments.map((link: any) => {
      const document = link.document;
      const requirement = link.requirementId ? requirements.get(link.requirementId) : null;
      const verification = document.verifications[0];
      return { documentId: document.id, requirement: requirement ? { requirementId: requirement.id, name: requirement.name, isRequired: requirement.isRequired } : null, label: link.label, documentType: document.documentType, expectedDocumentType: document.expectedDocumentType, originalFilename: document.originalFilename, mimeType: document.mimeType, fileSizeBytes: document.fileSizeBytes, status: document.status, rejectionReason: document.rejectionReason, uploadedAt: document.uploadedAt, review: verification ? { verificationId: verification.id, status: verification.status, failureReason: verification.failureReason, verifiedAt: verification.verifiedAt, createdAt: verification.createdAt, updatedAt: verification.updatedAt } : null, diagnostics: presentAdvisoryDiagnostics(document.aiExtractionResult) };
    }),
    mockIssuedDocumentAttachments: presentMockIssuedDocumentAttachments(app.mockIssuedDocumentAttachments, app.service.requirements),
    generatedDocuments: presentGeneratedDocuments(app.generatedDocuments),
    identityVerifications: app.verifications.map(presentIdentityVerification),
    history: app.statusHistory.map((entry: any) => ({ status: entry.status, note: entry.note, createdAt: entry.createdAt, changedBy: entry.changedBy ? { displayName: entry.changedBy.displayName, role: entry.changedBy.role } : null })),
  };
}
export function presentApplication(app: any) { return { ...presentQueueItem(app), correctionReason: app.correctionReason, applicationData: app.formData, citizen: { citizenId: app.citizen.id, fullName: app.citizen.fullName, city: app.citizen.city, state: app.citizen.state }, documents: app.applicationDocuments.map((link: any) => ({ documentId: link.document.id, requirementId: link.requirementId, documentType: link.document.documentType, expectedDocumentType: link.document.expectedDocumentType, originalFilename: link.document.originalFilename, mimeType: link.document.mimeType, fileSizeBytes: link.document.fileSizeBytes, status: link.document.status, rejectionReason: link.document.rejectionReason, uploadedAt: link.document.uploadedAt, verification: link.document.verifications[0] ? { status: link.document.verifications[0].status, failureReason: link.document.verifications[0].failureReason, verifiedAt: link.document.verifications[0].verifiedAt } : null })), mockIssuedDocumentAttachments: presentMockIssuedDocumentAttachments(app.mockIssuedDocumentAttachments, app.service.requirements ?? []), generatedDocuments: presentGeneratedDocuments(app.generatedDocuments), history: app.statusHistory.map((entry: any) => ({ status: entry.status, note: entry.note, createdAt: entry.createdAt, changedBy: entry.changedBy ? { displayName: entry.changedBy.displayName, role: entry.changedBy.role } : null })) }; }
export function presentDocument(document: any) { const link = document.applicationLinks[0]; const verification = document.verifications[0]; return { documentId: document.id, applicationId: link.applicationId, documentType: document.documentType, expectedDocumentType: document.expectedDocumentType, originalFilename: document.originalFilename, mimeType: document.mimeType, fileSizeBytes: document.fileSizeBytes, status: document.status, rejectionReason: document.rejectionReason, uploadedAt: document.uploadedAt, verification: verification ? { verificationId: verification.id, status: verification.status, failureReason: verification.failureReason, verifiedAt: verification.verifiedAt } : null, advisory: "Document analysis and OCR are advisory prototype inputs only; they do not verify authenticity or independently determine application outcomes." }; }
