process.env.NODE_ENV = "test";
process.env.PORT = "4001";
process.env.DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/janseva_x_test?schema=public";
process.env.JWT_SECRET = "test-secret-that-is-at-least-thirty-two-characters-long";
process.env.JWT_EXPIRES_IN = "1d";
process.env.REFRESH_TOKEN_EXPIRES_IN_DAYS = "7";
process.env.CORS_ORIGIN = "http://localhost:5173";
process.env.UPLOAD_DIR = "uploads";
process.env.MAX_FILE_SIZE_MB = "10";
