import { api, download } from "./client";
import type { ApplicationDetail, ApplicationSubmissionResult, ApplicationStatus, ApplicationSummary, CitizenProfile, DemoCitizenProfile, ExamSubmissionResult, FingerprintSession, GeneratedDocument, MockIssuedDocument, MockIssuedDocumentAttachment, Pagination, Service, SigningSession, SubmissionTicket, TokenPair, User, Verification, VerificationSummary } from "../types/api";

export const citizenApi = {
  register: (body: Record<string, unknown>) => api<{ user: User; tokens: TokenPair }>("/auth/register", { method: "POST", body, skipAuth: true }),
  login: (email: string, password: string) => api<{ user: User; tokens: TokenPair }>("/auth/login", { method: "POST", body: { email, password }, skipAuth: true }),
  demoLogin: (mobile: string, otp: string) => api<{ user: User; tokens: TokenPair }>("/auth/demo/login", { method: "POST", body: { mobile, otp }, skipAuth: true }),
  logout: (refreshToken: string) => api<void>("/auth/logout", { method: "POST", body: { refreshToken }, skipAuth: true }),
  me: () => api<{ user: User }>("/auth/me"),
  profile: () => api<{ profile: CitizenProfile }>("/citizen/profile"),
  updateProfile: (body: Record<string, unknown>) => api<{ profile: CitizenProfile }>("/citizen/profile", { method: "PATCH", body }),
  demoProfile: () => api<{ profile: DemoCitizenProfile }>("/citizen/demo-profile"),
  issuedDocuments: () => api<{ documents: MockIssuedDocument[] }>("/citizen/issued-documents"),
  issuedDocument: (id: string) => api<{ document: MockIssuedDocument }>(`/citizen/issued-documents/${id}`),
  services: () => api<{ services: Service[] }>("/services", { skipAuth: true }),
  exams: () => api<{ exams: unknown[] }>("/exams", { skipAuth: true }),
  exam: (id: string) => api<{ exam: unknown }>(`/exams/${id}`, { skipAuth: true }),
  createExamApplication: (examId: string) => api<{ application: unknown }>("/exam-applications", { method: "POST", body: { examId } }),
  examApplications: () => api<{ applications: unknown[] }>("/exam-applications"),
  examApplication: (id: string) => api<{ application: unknown }>(`/exam-applications/${id}`),
  updateExamApplication: (id: string, formData: Record<string, unknown>) => api<{ application: unknown }>(`/exam-applications/${id}`, { method: "PATCH", body: { formData } }),
  autoAttachExamDocuments: (id: string) => api<{ application: unknown; attached: string[] }>(`/exam-applications/${id}/auto-attach`, { method: "POST", body: {} }),
  validateExamApplication: (id: string) => api<{ valid: boolean; missingFields: string[]; missingRequirements: unknown[] }>(`/exam-applications/${id}/validate`, { method: "POST", body: {} }),
  submitExamApplicationIntent: (id: string, body: { idempotencyKey: string; clientCapturedAt: string; payloadHash: string }) => api<ExamSubmissionResult>(`/exam-applications/${id}/submission`, { method: "POST", body }),
  submitExamApplication: (id: string) => api<{ application: unknown; mode: string; payment: string }>(`/exam-applications/${id}/submit`, { method: "POST", body: {} }),
  setExamReminder: (id: string) => api<{ reminder: unknown }>(`/exam-applications/${id}/reminder`, { method: "POST", body: {} }),
  service: (id: string) => api<{ service: Service }>(`/services/${id}`, { skipAuth: true }),
  createApplication: (serviceId: string) => api<{ application: ApplicationSummary }>("/applications", { method: "POST", body: { serviceId } }),
  applications: (query = "") => api<{ applications: ApplicationSummary[]; pagination: Pagination }>(`/applications${query}`),
  application: (id: string) => api<{ application: ApplicationDetail }>(`/applications/${id}`),
  updateApplication: (id: string, applicationData: Record<string, unknown>) => api<{ application: ApplicationDetail }>(`/applications/${id}`, { method: "PATCH", body: { applicationData } }),
  history: (id: string) => api<{ history: ApplicationDetail["statusHistory"] }>(`/applications/${id}/history`),
  submit: (id: string, idempotencyKey?: string) => api<ApplicationSubmissionResult>(`/applications/${id}/submit`, { method: "POST", body: idempotencyKey ? { idempotencyKey } : {} }),
  submissionTicket: (id: string) => api<{ submissionTicket: SubmissionTicket }>(`/applications/${id}/submission-ticket`),
  retrySubmissionTicket: (id: string) => api<{ submissionTicket: SubmissionTicket }>(`/applications/${id}/submission-ticket/retry`, { method: "POST", body: {} }),
  complete: (id: string) => api<{ applicationId: string; status: ApplicationStatus; mode: string }>(`/applications/${id}/complete`, { method: "POST", body: {} }),
  documents: (id: string) => api<{ documents: ApplicationDetail["documents"] }>(`/applications/${id}/documents`),
  attachMockIssuedDocument: (applicationId: string, body: { mockIssuedDocumentId: string; requirementId: string }) => api<{ attachment: MockIssuedDocumentAttachment }>(`/applications/${applicationId}/mock-issued-document-attachments`, { method: "POST", body }),
  upload: (id: string, form: FormData) => api<{ document: ApplicationDetail["documents"][number] }>(`/applications/${id}/documents`, { method: "POST", body: form }),
  deleteDocument: (id: string) => api<void>(`/documents/${id}`, { method: "DELETE" }),
  analyze: (id: string) => api<{ document: ApplicationDetail["documents"][number]; analysis: Record<string, unknown>; mode: string }>(`/documents/${id}/analyze`, { method: "POST", body: {} }),
  analysis: (id: string) => api<{ analysis: Record<string, unknown> | null; mode: string }>(`/documents/${id}/verification`),
  aadhaar: (appId: string, aadhaar: string) => api<Verification>(`/applications/${appId}/verifications/aadhaar`, { method: "POST", body: { aadhaar } }),
  pan: (appId: string, pan: string) => api<Verification>(`/applications/${appId}/verifications/pan`, { method: "POST", body: { pan } }),
  startFace: (appId: string) => api<Verification>(`/applications/${appId}/verifications/face/start`, { method: "POST", body: {} }),
  completeFace: (id: string) => api<Verification>(`/verifications/${id}/face/complete`, { method: "POST", body: {} }),
  startFingerprint: (appId: string) => api<FingerprintSession>(`/applications/${appId}/verifications/fingerprint/start`, { method: "POST", body: {} }),
  pairFingerprint: (id: string, pairingChallenge: string) => api<FingerprintSession>(`/fingerprint-sessions/${id}/pair`, { method: "POST", body: { pairingChallenge } }),
  completeFingerprintStep: (id: string, step: string) => api<FingerprintSession>(`/fingerprint-sessions/${id}/steps/${step}/complete`, { method: "POST", body: {} }),
  fingerprintStatus: (id: string) => api<FingerprintSession>(`/fingerprint-sessions/${id}/status`),
  ekyc: (appId: string) => api<Verification>(`/applications/${appId}/verifications/ekyc`, { method: "POST", body: {} }),
  verificationSummary: (appId: string) => api<VerificationSummary>(`/applications/${appId}/verifications/summary`),
  generated: (appId: string) => api<{ documents: GeneratedDocument[] }>(`/applications/${appId}/generated-documents`),
  generatedDetail: (id: string) => api<{ document: GeneratedDocument }>(`/generated-documents/${id}`),
  downloadGenerated: (id: string) => download(`/generated-documents/${id}/download`),
  startSigning: (id: string) => api<SigningSession>(`/generated-documents/${id}/signing-sessions`, { method: "POST", body: {} }),
  completeSigning: (id: string, signingChallenge: string, consentVersion: string) => api<{ applicationStatus: ApplicationStatus; generatedDocumentId: string; sessionId: string; state: string; mode: string }>(`/generated-document-signing-sessions/${id}/complete`, { method: "POST", body: { signingChallenge, consentAccepted: true, consentVersion } }),
};
